"""Abstract interface for Vaarta persistence."""

from pathlib import Path
from typing import Optional, Protocol


class StoreProtocol(Protocol):
    """Protocol for form/session/file storage. Implement for file or PostgreSQL."""

    def save_form(self, form_id: str, data: dict) -> None: ...
    def load_form(self, form_id: str) -> Optional[dict]: ...
    def list_forms(self) -> list[dict]: ...
    def update_form_fields(self, form_id: str, fields: list, title: str) -> bool: ...
    def update_form_sample_values(self, form_id: str, sample_values: dict) -> bool: ...
    def update_form_health_score(self, form_id: str, health: dict) -> bool: ...

    def save_original(self, form_id: str, file_bytes: bytes, suffix: str) -> str: ...
    def original_path(self, form_id: str) -> Optional[Path]: ...

    def save_session(self, session_id: str, data: dict) -> None: ...
    def load_session(self, session_id: str) -> Optional[dict]: ...
    def list_sessions_for_form(self, form_id: str) -> list[dict]: ...

    def filled_path(self, session_id: str) -> Path: ...

    def save_session_file(
        self, session_id: str, field_name: str, file_bytes: bytes, suffix: str
    ) -> str: ...
    def get_session_file(self, field_name: str, session_id: str) -> Optional[bytes]: ...
    def list_session_files(self, session_id: str) -> list[dict]: ...
